server:
  port: 8086

spring:
  application:
    name: cloud-payment
  datasource:
    url: jdbc:mysql://${MYSQL_ADDR:${VM_HOST:localhost}:3306}/cloud_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root123}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:${VM_HOST:localhost}:8848}
        username: nacos
        password: nacos
      config:
        server-addr: ${NACOS_ADDR:${VM_HOST:localhost}:8848}
        file-extension: yml
    sentinel:
      transport:
        dashboard: ${SENTINEL_ADDR:${VM_HOST:localhost}:8858}
      eager: true
  kafka:
    bootstrap-servers: ${KAFKA_ADDR:${VM_HOST:localhost}:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: payment-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true

knife4j:
  enable: true
