server:
  port: 8080

spring:
  application:
    name: cloud-gateway
  codec:
    max-in-memory-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:${VM_HOST:localhost}:8848}
        namespace: ${NACOS_NAMESPACE:}
        username: nacos
        password: nacos
      config:
        server-addr: ${NACOS_ADDR:${VM_HOST:localhost}:8848}
        file-extension: yml
        import-check.enabled: false
    sentinel:
      transport:
        dashboard: ${SENTINEL_ADDR:${VM_HOST:localhost}:8858}
      eager: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: cloud-auth
          uri: lb://cloud-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: cloud-user
          uri: lb://cloud-user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: cloud-product
          uri: lb://cloud-product
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=1
        - id: cloud-cart
          uri: lb://cloud-cart
          predicates:
            - Path=/api/cart/**
          filters:
            - StripPrefix=1
        - id: cloud-order
          uri: lb://cloud-order
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1
        - id: cloud-payment
          uri: lb://cloud-payment
          predicates:
            - Path=/api/payment/**
          filters:
            - StripPrefix=1
